version: '2.0'

services:
  otp:
    image:  urbica/otp
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./graphs:/var/otp/graphs
    environment:
      - JAVA_OPTIONS=-Xmx2G
    command:
      [
        '--load /var/otp/graphs/portland',
        '--maxThreads 4'
      ]
